'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WcfDemoServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WcfDemoServiceReference.IWcfDemo")>  _
    Public Interface IWcfDemo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDemo/SendEmail", ReplyAction:="http://tempuri.org/IWcfDemo/SendEmailResponse")>  _
        Function SendEmail() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDemo/SendEmail", ReplyAction:="http://tempuri.org/IWcfDemo/SendEmailResponse")>  _
        Function SendEmailAsync() As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWcfDemoChannel
        Inherits WcfDemoServiceReference.IWcfDemo, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WcfDemoClient
        Inherits System.ServiceModel.ClientBase(Of WcfDemoServiceReference.IWcfDemo)
        Implements WcfDemoServiceReference.IWcfDemo
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SendEmail() As String Implements WcfDemoServiceReference.IWcfDemo.SendEmail
            Return MyBase.Channel.SendEmail
        End Function
        
        Public Function SendEmailAsync() As System.Threading.Tasks.Task(Of String) Implements WcfDemoServiceReference.IWcfDemo.SendEmailAsync
            Return MyBase.Channel.SendEmailAsync
        End Function
    End Class
End Namespace
